import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/navBar";
import TanstackProvider from "@/components/providers/TanstackProvider";
import { AuthProvider } from "@/components/providers/AuthContext";

import { Auth } from "../components/Auth";


const inter = Inter({ subsets: ["latin"] });
const backgroundStyle = {
  backgroundSize: "cover",
  backgroundRepeat: "no-repeat",
  height: "100vh",
};

export const metadata: Metadata = {
  title: "lmi9wad",
  description: "Generated by gyro",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { pathname } = route;
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0 maximum-scale=1.0 minimum-scale=1.0"
        />
        <link rel="icon" href="/logo.png" />
      </head>
      <body style={backgroundStyle} className=" max-w-[1500px] mx-auto ">
        <AuthProvider>
          <TanstackProvider>
            <main className=" relative flex flex-col justify-center items-center h-[calc(100vh-80px)] md:h-[100%] ">
              <Auth ></Auth>
              {children}
            </main>
          </TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
