version: "3.5"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: ./backend
    container_name: backend
    image: backend
    restart: "always" 
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
      - "5555:5555"

  client:
    depends_on:
    - app
    build: ./frontend
    container_name: frontend
    image: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: "always"
